name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/automated-deployment-service
            git pull origin main

            docker build -f docker/Dockerfile -t automated-deployment-service .

            docker stop automated-app || true
            docker rm automated-app || true

            docker run -d --name automated-app -p 8080:80 automated-deployment-service

            sleep 5

            if curl -f http://localhost:8080/ > /dev/null; then
              echo "HEALTH CHECK: PASSED"
            else
              echo "HEALTH CHECK: FAILED"
              docker logs automated-app
              exit 1
            fi